version: '3'

services:
  web:
    build: .
    command: >
      bash -c
      volumes:
      - .:/code
      - static-volume:/code/static
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - db_network
      - web_network
    command: "./wait-for-it.sh db:3306 -- bash -c \"pwd && ls && cd mysite && ls && python3 manage.py makemigrations && python3 manage.py makemigrations mysite && python3 manage.py makemigrations showactivity && python3 manage.py migrate && uwsgi --socket 0.0.0.0:8000 --wsgi-file mysite/wsgi.py\""
  db:
    image: mysql/mysql-server:5.7.27
    volumes:
     - "./mysql:/var/lib/mysql"
    ports:
     - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: 'THUVPlus'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '123'
    networks:
     - db_network
  nginx:
    restart: always
    image: nginx:1.14.0
    ports:
      - "0.0.0.0:443:443"
    volumes:
      - static-volume:/code/static
      - ./ssl:/ssl
      - ./config/nginx_conf:/etc/nginx/conf.d
      - ./config/nginx:/thuvplus
      - ./log/nginx:/var/log/nginx
    depends_on:
      - web
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge
volumes:
  static-volume:
